import 'dart:convert';
import 'dart:io';

import 'package:acu_lidar_console/core/reference.dart';
import 'package:acu_lidar_console/widgets/device_meshes.dart';
import 'package:acu_lidar_console/widgets/vehicle_plan.dart' show heightOf;
import 'package:flutter_test/flutter_test.dart';

/// Dumps the device geometry so the Blender step can put it inside the vehicle body.
///
/// It lives in the test folder because that is the only way to run this package's code from the
/// command line: `device_meshes.dart` reaches dart:ui for Color, and `dart run` has no engine
/// under it. Writing the geometry out from a second implementation in Python was the alternative,
/// and two copies of the same shapes drift the first time either is touched.
///
///     flutter test test/export_devices_test.dart
///     # -> build/devices.json
void main() {
  test('export device geometry for the Blender scene build', () {
    final devices = <Map<String, dynamic>>[];

    for (final n in allNodes) {
      // Cameras are left out: ten of them inside a translucent shuttle is a fog of small dark
      // boxes, and they are named in the port bar and the inspector instead.
      if (n.kind == NodeKind.camera) continue;
      final mesh = meshFor(n);
      devices.add({
        'id': n.id,
        'name': n.name,
        'kind': n.kind.name,
        // Normalised, like the hotspots: x lateral -1..1, y 0 front to 1 rear, z height 0..1.
        // The Blender step resolves them against whatever body it is given.
        'nx': n.pos.dx,
        'ny': n.pos.dy,
        'nz': heightOf(n),
        'yaw': headingFor(n),
        'quads': [
          for (final q in mesh.quads)
            {
              'c': ((q.colour.r * 255).round() << 16) |
                  ((q.colour.g * 255).round() << 8) |
                  (q.colour.b * 255).round(),
              'a': q.alpha,
              'p': [
                for (final v in q.p) [v.x, v.y, v.z],
              ],
            },
        ],
      });
    }

    final out = File('build/devices.json');
    out.parent.createSync(recursive: true);
    out.writeAsStringSync(jsonEncode({
      'note': 'generated by test/export_devices_test.dart — do not edit',
      'exaggeration': deviceExaggeration,
      'devices': devices,
    }));

    final quads = devices.fold<int>(0, (a, d) => a + (d['quads'] as List).length);
    // ignore: avoid_print
    print('wrote ${out.path}: ${devices.length} devices, $quads quads');
    expect(devices.length, greaterThan(10));
    expect(quads, greaterThan(500));
  });
}
