#!/usr/bin/env node
// Resolve YANG paths to SIDs and emit a C header for the switch-controller firmware.
//
// Why generate instead of shipping the catalog: the device's YANG catalog is 54 files and
// 1.6 MB of JSON. The firmware needs a handful of SIDs from it. Resolving on a PC and baking
// the answers keeps the ESP free of a JSON parser and of the memory to run one.
//
// Why the checksum travels with the table: SIDs belong to a catalog, and catalogs differ
// between devices -- the bench LAN9662 and the target LAN9692 do not have the same module set.
// A table used against the wrong catalog would address the wrong nodes and report plausible
// nonsense. So the checksum is baked in beside the SIDs and the firmware refuses a device that
// reports a different one.
import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';

const CLI = process.env.KETI_TSN_CLI ?? '/home/kim/keti-tsn-cli-new';
const { loadYangInputs } = await import(`${CLI}/tsc2cbor/lib/common/input-loader.js`);
const { resolvePathToSid } = await import(`${CLI}/tsc2cbor/lib/common/sid-resolver.js`);

const here = path.dirname(new URL(import.meta.url).pathname);
const pathsFile = process.argv[2] ?? path.join(here, 'paths.yaml');
const outFile = process.argv[3] ??
  path.join(here, '../../firmware/switch_controller/sid_table.h');

// The cache directory is named after the catalog checksum, which is exactly the identifier
// that has to end up in the header.
const cacheRoot = path.join(CLI, 'tsc2cbor/.yang-cache');
const catalogs = fs.readdirSync(cacheRoot, { withFileTypes: true })
  .filter(e => e.isDirectory())
  .map(e => e.name);

// More than one device has been on this bench, so which catalog to build against is a choice
// and not something to infer. Name it with KETI_CATALOG; the table it produces is only valid
// for the device that reports that checksum, and the firmware refuses any other.
const wantedCatalog = process.env.KETI_CATALOG;
if (!wantedCatalog && catalogs.length !== 1) {
  console.error(`${catalogs.length} cached catalogs in ${cacheRoot}:`);
  for (const c of catalogs) console.error(`  ${c}`);
  console.error('set KETI_CATALOG to the one this firmware is for');
  process.exit(1);
}
const checksum = wantedCatalog ?? catalogs[0];
if (!catalogs.includes(checksum)) {
  console.error(`catalog ${checksum} is not cached; run "keti-tsn download" against that device`);
  process.exit(1);
}
const cacheDir = path.join(cacheRoot, checksum);

const wanted = yaml.load(fs.readFileSync(pathsFile, 'utf8'));
if (!Array.isArray(wanted) || wanted.length === 0) {
  console.error(`${pathsFile} must be a non-empty list of YANG paths`);
  process.exit(1);
}

const { sidInfo } = await loadYangInputs(cacheDir, false);

// The catalog keys its paths without a leading slash, but every human and every YAML file in
// keti-tsn-cli writes one. Accept both and normalise rather than making the caller remember.
const normalise = p => (p.startsWith('/') ? p.slice(1) : p);

const entries = [];
const failures = [];
for (const p of wanted) {
  const key = normalise(p);
  const sid = resolvePathToSid(key, sidInfo);
  if (sid == null) failures.push(p);
  else entries.push({ path: key, sid });
}

if (failures.length) {
  // Emitting a partial table would hand the firmware a silent hole: it would ask for the
  // paths that did resolve and simply never mention the ones that did not.
  console.error('these paths did not resolve against this catalog:');
  for (const p of failures) console.error(`  ${p}`);
  process.exit(1);
}

const lines = [];
lines.push('// Generated by tools/gen_sid_table/generate.mjs -- do not edit by hand.');
lines.push('//');
lines.push('// SIDs are only meaningful against the catalog they came from, so the checksum');
lines.push('// below travels with them. The firmware compares it against what the device');
lines.push('// reports and refuses to run rather than address the wrong nodes.');
lines.push('#pragma once');
lines.push('');
lines.push('#include <stdint.h>');
lines.push('');
lines.push(`#define KETI_SID_CATALOG_CHECKSUM "${checksum}"`);
lines.push('');
lines.push('// The one SID that cannot be generated, because it is what you ask for before you');
lines.push('// know which catalog you are talking to.');
lines.push('#define KETI_SID_YANG_CHECKSUM 29304u');
lines.push('');
lines.push('struct KetiSidEntry {');
lines.push('  const char *path;');
lines.push('  uint32_t sid;');
lines.push('};');
lines.push('');
lines.push('static const KetiSidEntry kKetiSidTable[] = {');
for (const e of entries) lines.push(`    {"${e.path}", ${e.sid}u},`);
lines.push('};');
lines.push('');
lines.push(`static constexpr int kKetiSidCount = ${entries.length};`);
lines.push('');
lines.push('inline uint32_t ketiSidFor(const char *path) {');
lines.push('  for (int i = 0; i < kKetiSidCount; ++i) {');
lines.push('    const char *a = kKetiSidTable[i].path, *b = path;');
lines.push('    while (*a && *a == *b) { ++a; ++b; }');
lines.push('    if (*a == 0 && *b == 0) return kKetiSidTable[i].sid;');
lines.push('  }');
lines.push('  return 0;  // caller must treat 0 as "not in the table", never as a valid SID');
lines.push('}');
lines.push('');

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, lines.join('\n'));

console.log(`catalog ${checksum}`);
for (const e of entries) console.log(`  ${String(e.sid).padStart(8)}  ${e.path}`);
console.log(`wrote ${entries.length} entries to ${path.relative(process.cwd(), outFile)}`);
