// Generated by tools/gen_sid_table/generate.mjs -- do not edit by hand.
//
// SIDs are only meaningful against the catalog they came from, so the checksum
// below travels with them. The firmware compares it against what the device
// reports and refuses to run rather than address the wrong nodes.
#pragma once

#include <stdint.h>

#define KETI_SID_CATALOG_CHECKSUM "440057a11e66eed82bc8e838347f694c"

// The one SID that cannot be generated, because it is what you ask for before you
// know which catalog you are talking to.
#define KETI_SID_YANG_CHECKSUM 29304u

struct KetiSidEntry {
  const char *path;
  uint32_t sid;
};

static const KetiSidEntry kKetiSidTable[] = {
    {"ietf-interfaces:interfaces", 2005u},
    {"ietf-system:system-state/platform", 19024u},
    {"ietf-interfaces:interfaces/interface", 2033u},
    {"ietf-interfaces:interfaces/interface/name", 2042u},
    {"ietf-interfaces:interfaces/interface/oper-status", 2043u},
    {"ietf-interfaces:interfaces/interface/statistics", 2046u},
    {"ietf-interfaces:interfaces/interface/phys-address", 2044u},
    {"ietf-interfaces:interfaces/interface/statistics/in-octets", 2052u},
    {"ietf-interfaces:interfaces/interface/statistics/out-octets", 2059u},
    {"ietf-interfaces:interfaces/interface/statistics/in-errors", 2050u},
    {"ietf-interfaces:interfaces/interface/statistics/out-errors", 2057u},
    {"ietf-interfaces:interfaces/interface/statistics/in-discards", 2049u},
    {"ietf-interfaces:interfaces/interface/statistics/out-discards", 2056u},
    {"ietf-interfaces:interfaces/interface/statistics/in-unicast-pkts", 2053u},
    {"ietf-interfaces:interfaces/interface/statistics/out-unicast-pkts", 2060u},
    {"ietf-system:system-state/platform/machine", 19025u},
    {"ietf-system:system-state/platform/os-version", 19028u},
    {"ietf-interfaces:interfaces/interface/enabled", 2036u},
    {"ietf-interfaces:interfaces/interface/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table", 23101u},
    {"ietf-interfaces:interfaces/interface/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/gate-enabled", 23125u},
    {"ietf-interfaces:interfaces/interface/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/oper-gate-states", 23139u},
    {"ietf-interfaces:interfaces/interface/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/admin-cycle-time/numerator", 23114u},
    {"ietf-interfaces:interfaces/interface/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/admin-cycle-time/denominator", 23113u},
    {"ietf-interfaces:interfaces/interface/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/admin-control-list/gate-control-entry", 23106u},
};

static constexpr int kKetiSidCount = 24;

inline uint32_t ketiSidFor(const char *path) {
  for (int i = 0; i < kKetiSidCount; ++i) {
    const char *a = kKetiSidTable[i].path, *b = path;
    while (*a && *a == *b) { ++a; ++b; }
    if (*a == 0 && *b == 0) return kKetiSidTable[i].sid;
  }
  return 0;  // caller must treat 0 as "not in the table", never as a valid SID
}
